config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root "quotes#index"
  resources :quotes do
    get :panel, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
  validates :name, presence: true, allow_blank: false
  broadcasts_refreshes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  def panel
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        Turbo::StreamsChannel.broadcast_refresh_to @quotes
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy!
    Turbo::StreamsChannel.broadcast_refresh_to @quotes
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(@quote) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireTests</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <% #= turbo_refreshes_with method: :replace, scroll: :reset %>
    <%= turbo_refreshes_with method: :morph, scroll: :preserve %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="quote">
  <div class="input-field">
    <%= form.text_field :name, class:"input" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
</div>

<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
  <div class="quote" id="<%= dom_id quote %>" data-controller="quote">
    <blockquote>
        <p class="tooltip" tip="click here for stimulus test" data-quote-target='name' data-action="click->quote#getQuoteName"><%= "#{quote.name}"%></p>
        <%= link_to quote.name, quote, data: {turbo_frame: "_top"} %>
      </p>
      <div class="buttons"  >
        <%= button_to "Edit", edit_quote_path(quote), method: :get %>
        <%= button_to "Delete", quote_path(quote), data: {turbo_frame: "_top", turbo_confirm: "Are you sure?"}, method: :delete %>
      </div>
    </blockquote>
  </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= turbo_frame_tag @quote do %>
 <%= render "form", quote: @quote %>
 <%= button_to sanitize("&larr; Back"), quotes_path, method: :get %>
<% end %>

<br>

<div>
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<div id="container">
  <%= turbo_stream_from "quotes_broadcaster" %>

  <details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
  </details>
  <div id="left">
    <%= button_to "New quote", new_quote_path, data: {turbo_frame: dom_id(Quote.new)}, method: :get %>
    <div>
			<%= turbo_frame_tag Quote.new %>
		</div>
  </div>
  <div id="right">
    <h1>
      Quotes
    </h1>
    <%= turbo_frame_tag "quotes" do %>
      <%= render @quotes %>
     <% end %>
  </div>
</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>
    <%= turbo_frame_tag Quote.new do %>
      <%= render "form", quote: @quote %>
      <%= button_to sanitize("&larr; Close"), quotes_path, method: :get %>
    <% end %>
<br>

<div>
  <%= link_to "Back to quotes", quotes_path %>

</div>

app/views/quotes/panel.html.erb
<div id="container">
  <%= turbo_stream_from "quotes_broadcaster" %>

  <details>
    <summary>Details</summary>
    Something small enough to escape casual notice.
  </details>
  <div>
    <h1>
      Quotes
    </h1>
    <%= turbo_frame_tag "quotes" do %>
      <%= render @quotes %>
     <% end %>
  </div>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <%= button_to sanitize("&larr; Close"), quotes_path, method: :get %>
</div>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.prepend "quotes", @quote %>
<%= turbo_stream.update Quote.new, "" %>